version: "3.9"
services:
  cachedrepository:
    build: .
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      MSSQL_SA_PASSWORD: "V3ry_Secur3_P@SSw0rd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"